### ISSUE TITLE
Update for Rust Beta and follow style guide

### ISSUE THREAD

**Issue by alexschneider** [rtoal/ple#31]
Rust 1.0 beta [came out today](http://blog.rust-lang.org/2015/04/03/Rust-1.0-beta.html). Also coming out in the near future is the (yet incomplete) [style guide](http://doc.rust-lang.org/nightly/style). We should update the Rust code to be idiomatic (and to fix any non-compilation issues).

**Comment by jadengore** [comment]
@alexschneider Should we close this since 1.0 has been official for a while?

**Comment by rtoal** [comment]
Current code runs under 1.80 so I think we can call things up to date. There are still a few in the underconstruction folder but we can get to these over time
