### ISSUE TITLE
Implement examples in Nim

### ISSUE THREAD

**Issue by AuthorOfTheSurf** [rtoal/ple#32]
[Nim](http://nim-lang.org/) is an interesting language that handles concurrency in a way that I haven't seen before. I found out about it because it killed it on the [EC2 multiple queries and updates tests](https://www.techempower.com/benchmarks/#section=data-r10&hw=ec2&test=query). I've taken a little look at it and it's one of the more interesting things I've seen.
- [Nim by example](http://nim-by-example.github.io/)

**Comment by rtoal** [comment]
Agreed. Please start by porting the triple, anagrams, and wordcount programs from Go. Thanks!

**Comment by rtoal** [comment]
Still interested in this, @AuthorOfTheSurf ?

**Comment by AuthorOfTheSurf** [comment]
I don't think that I can make this happen Dr. @rtoal!
