### ISSUE TITLE
JavaScript - empty object is not a falsy value

### ISSUE THREAD

**Issue by SamuraiPrinciple** [rtoal/ple#45]
Lovely book - am really enjoying it!

Not really sure if this is the right place for errata.

Noticed a small error while reading a chapter on JavaScript - in the wrap-up section empty object is listed as a falsy falue (it's actually truthy).

**Comment by rtoal** [comment]
Thank you, much appreciated! I added an Errata item at http://rtoal.github.io/ple/ and credited you as the discoverer. Again, many thanks.
